[package]
name = "carbon-mpl-token-metadata-decoder"
version = "0.4.0"
description = "MPL Token Metadata Decoder"
license = "MIT"
edition = "2018"

[lib]
crate-type = ["rlib"]

[dependencies]
carbon-core = { workspace = true }
solana-sdk = "2.0.10"
serde = "1.0.136"
