[package]
name = "carbon-cli"
version = "0.4.0"
edition = "2018"
description = "CLI for Carbon"
license = "MIT"

[[bin]]
name = "carbon-cli"
path = "src/main.rs"

[dependencies]
carbon-core = { workspace = true }
solana-sdk = { workspace = true }
solana-transaction-status = { workspace = true }
solana-client = { workspace = true }

anyhow = "1.0.86"
serde_json = "1.0.125"
serde = { version = "1.0.208", features = ["derive"] }
borsh = { version = "1.5.1", features = ["derive"] }
console = "0.15.8"
dialoguer = { version = "0.11.0", default-features = false, features = [
    "editor",
] }
indicatif = "0.17.8"
clap = { version = "4.5.4", features = ["derive"] }
askama = "0.12.1"
hex = "0.4.3"
sha2 = "0.10.8"
heck = "0.5.0"
flate2 = "1.0.35"
