[package]
name = "carbon-memo-program-decoder"
version = "0.4.0"
description = "Memo Program Decoder"
license = "MIT"
edition = "2018"

[lib]
crate-type = ["rlib"]

[dependencies]
carbon-core = { workspace = true }
solana-sdk = "2.0.10"
serde = "1.0.136"
spl-token = "6.0.0"
spl-memo = "5.0.0"
