[package]
name = "carbon-proc-macros"
version = "0.4.0"
edition = "2018"
description = "Procedural macros for Carbon"
license = "MIT"

[lib]
proc-macro = true

[dependencies]
solana-transaction-status = { workspace = true }
solana-client = { workspace = true }
solana-sdk = { workspace = true }

syn = { version = "1.0", features = ["full"] }
paste = "1.0.15"
quote = "1.0"
hex = "0.4.3"
serde = "1.0.136"
borsh-derive-internal = "0.10.3"
proc-macro2 = "1"
unicode-xid = "0.2"
