[package]
name = "carbon-jupiter-dca-decoder"
version = "0.4.0"
description = "Jupiter DCA Decoder"
license = "MIT"
edition = "2018"

[lib]
crate-type = ["rlib"]

[dependencies]
carbon-core = { workspace = true }

solana-sdk = "2.0.10"
serde = "1.0.136"
