[package]
name = "carbon-log-metrics"
version = "0.4.0"
description = "Log Metrics"
license = "MIT"
edition = "2021"

[dependencies]
carbon-core = { workspace = true }

tokio = { version = "1.17.0", features = ["full"] }
async-trait = "0.1.82"
log = "0.4.22"

[lib]
crate-type = ["rlib"]
