[package]
name = "carbon-raydium-clmm-decoder"
version = "0.4.0"
description = "Raydium CLMM Decoder"
edition = "2018"
license = "MIT"

[lib]
crate-type = ["rlib"]

[dependencies]
carbon-core = { workspace = true }
carbon-proc-macros = { workspace = true }
carbon-macros = { workspace = true }
solana-sdk = "2.0.10"
serde = "1.0.136"

